from docx import Document
from docx.shared import Inches
import pyttsx3


def speak(text):
    pyttsx3.speak(text)


def add_experience(paragraph):
    company = input("Write company\n")
    from_date = input("From date\n")
    to_date = input("To date\n")

    paragraph.add_run(company + " ").bold = True
    paragraph.add_run(from_date + "-" + to_date + "\n").italic = True

    experience_details = input("Dicover your experiense at " + company + "\n")
    paragraph.add_run(experience_details + "\n")

def add_skill(document):
    skill_paragraph = document.add_paragraph()
    skill_paragraph.style = "List Bullet"
    skill = input("Write your skill\n")
    skill_paragraph.add_run(skill)


document = Document()

document.add_picture("Photo.jpeg", width = Inches(1.5))

name = input("Type your name:\n")
speak("Hello " + name)
phone_number = input("Type your phone number:\n")
email = input("Type your email:\n")

document.add_paragraph(
    name + " | " + phone_number + " | " + email
)

document.add_heading("About me")
new_var = input("Tell about yourself:\n")
document.add_paragraph(new_var)

document.add_heading("Work experience")
experience_paragraph = document.add_paragraph()

print("Tell us something about your work experience")


add_experience(experience_paragraph)

while True:
    has_more_experience = input("Do you have more work experience? Yes or no\n").lower()
    if has_more_experience == "yes":
        add_experience(experience_paragraph)
    else:
        break


document.add_heading("Skills")
print("Let's discuss your skills")

add_skill(document)
while True:
    has_more_skills = input("Do you have more skills? Yes or no\n").lower()
    if has_more_skills == "yes":
        add_skill(document)
    else:
        break

# footer
section = document.sections[0]
footer = section.footer
footer_paragraph = footer.paragraphs[0]
footer_paragraph.text = "CV generated by Ivan Baklanov"

document.save("cv.docx")